### ISSUE TITLE
App öffnet nicht in Mac mini M1

### ISSUE THREAD

**Issue by ptrou** [CanYumusak/AnDrop#14]
AnDrop 1.2 öffnet nicht nach Installation aus dem App Store
Mac mini M1 (2020)
13.3.1 (22E261)

**Comment by CanYumusak** [comment]
Hey @ptrou, Kannst du mir mitteilen welches Problem du genau siehst? Normalerweise sollte das Icon oben Rechts in der Leiste erscheinen. Fehlt es?
